language: python
python:
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - flake8 --max-line-length=100
