language: python
python:
- '3.7'
cache: pip
install:
- pip install -r requirements.txt
script:
- bash scripts/static_analysis.sh
deploy:
  provider: heroku
  api_key:
    secure: BX1JVxcDBlf8CQJMRUx32ri7Kn7PV5ADPnKVGYy38/rUscybBZOb1WsbpvgFw/M0OsHItmrNR+mH5yip+zQevSS7NO45VAtU/Aoe+ZFnD46JsGyHxuXudzuuv/ABwM5wlj0KDQ8yZ7QIItcv4s4RQNXvRHEOW0CIAVh9OWqgcAy1xUGAE3TSqgHJgSHNOvBWlzs7UqVPoR7DoFWUxD3VzUL9MJurwD3E7F7WgNz26n7R8nGa9MawfaSmeR3LkK7ivF2nc5q0TqivYY/ofpfq2eyre1AouvbtnlvtwRqZ+6qhYSGHgJkQaww9TwHVgQfN06hxWGPCGoSFrt9CtXt+GKLrcdhZ7HYEPEjeWb59exxKKPhkeNFQ+GjfzP8WE5MxsEL0Hm+3d51OY+kopw2FSTVKpekQP1pGeDXasu/QCK92eU1ArD10zhuaKVq5yOyPFh685O83eH3//nhZvpssrUgOUe1FPaGuz562cIhbQYKrFX6yvzMYl3kxvd4jq/PqWWsy5MLksQlSGXww4nQ0j8UnYr8HuGOWnQNPtnWXVgz65Vt5SPJ7tROxtJPTFOF/dPFCu2RCSTc33APTXJwFMt2FlUYkYRA2SglrL3eehEv4oSYnRC8CDtrEBJsccv5Pb9WVvw1dUECT4N0BCTcRlCyArmglaIa/cclMpXBzSvo=
  app: malaria-visualiser
